source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sinatra-cors'
gem 'natural_20', '~> 0.5.0'
gem 'sqlite3', '~> 1.6'
gem 'activerecord', '~> 7.0'
gem 'rack', '~> 2.2'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'
# gem 'ruby-openai', '~> 3.0'  # Uncomment when you have OpenAI API key
